[tool.poetry]
name = "try-hello-tdcc-nes"
version = "0.1.0"
description = ""
authors = ["Ian van der Neut <neutvd@knmi.nl>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
