on:
  push:
    paths:
      - 'docs/**'

jobs: 
  publish-gh-pages:
    name: "Publish GitHub pages"
    runs-on: ubuntu-latest
    steps:
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5
